### ISSUE TITLE
Heall All on Vault

### ISSUE THREAD

**Issue by dlg2267** [halbu/fs-halbui#2]
The Heal All button is not visible during an event.
It is visible once the event is over.

**Comment by halbu** [comment]
Can I ask for a bit more detail on this one? Nobody has encountered this in testing and I am unable to reproduce - during both attacks and incidents the button appears to work. Does the button disappear immediately?

**Comment by retropwned** [comment]
i only notice that in the very first room, the vault door room (during an event). seems to work fine in every other room (during an event) although i think you need to be clicked on that room and not sure but i think at least one dweller needs to be healed (due to the event). still testing.

**Comment by dlg2267** [comment]
Yes, only the vault door.  Will try to get a screen cap.

**Comment by dlg2267** [comment]
![HealAll](https://user-images.githubusercontent.com/11761545/78899700-c1bce100-7a43-11ea-84f5-0bd09cbae254.png)

**Comment by dlg2267** [comment]
I am using the Bethesda version if that matters ...

**Comment by retropwned** [comment]
i think it might matter yes, play testing done with steam but i have same issue.
