### ISSUE TITLE
fs-halbui open menu icon on startup.

### ISSUE THREAD

**Issue by retropwned** [halbu/fs-halbui#4]
not a bug but would be nice if the halbui menu icon in the upper right corner could remember if you want to keep it opened or closed on game startup.

**Comment by halbu** [comment]
Totally reasonable request and hopefully one that shouldn't take a great deal of development effort. I'll try and make sure this goes into the next release.

**Comment by retropwned** [comment]
it works wonderfully. thankx bruh.
